server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:mysql://104.198.225.31/test?useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 031805
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

# MySQL - 8.0.28
spring:
  datasource:
    username: root
    password: dbuserdbuser
    # serverTimezone=UTC解决时区报错
    url: jdbc:mysql://localhost:3306/classicmodels?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UCT
#    url: jdbc:mysql://localhost:3306/classicmodels?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis:
#  mapper-locations: classpath:mapper/*.xml