server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://104.198.225.31/test?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 031805
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

dataproc:
  project-id: whattoeattoday-401920
  region: us-central1
  cluster-name: cluster-9428