name: Java CI

on:
  push:
    branches: [ main ,yf1125]
  pull_request:
    branches: [ main ,yf1125]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package

      - name: Run Tests with Coverage
        run: mvn test jacoco:report

      - name: Analyze code quality
        run: mvn checkstyle:checkstyle pmd:pmd

      - name: Set up Node.js for Newman
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Start service
        run: mvn spring-boot:run &
      - name: Wait for service to start
        run: sleep 10

      - name: Run Postman tests
        run: newman run ./RecommendationService.postman_test_run.json

      - name: Generate and upload test report
        run: |
          newman run ./RecommendationService.postman_test_run.json --reporters cli,junit --reporter-junit-export results.xml
        if: always()

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: postman-test-reports
          path: results.xml

